title: OpenDSU Project
description: https://www.opendsu.org
theme: just-the-docs

#logo: "LOGO.png"

favicon_ico: "LOGO.png"

url: https://www.opendsu.org

repository: https://github.com/opendsu/ # for github-metadata

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

aux_links:
  "OpenDSU on GitHub":
    - "https://github.com/opendsu/"

    # Makes Aux links open in a new tab. Default is true
aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: OpenDSU on GitHub
    url: https://github.com/opendsu/

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false


callouts:
  accepted:
    title: accepted
    color: green
  feedback:
    title: feedback
    color: yellow
  proposal:
    title: proposal
    color: blue
  draft:
    title: draft
    color: grey-dk
  replaced:
    title: replaced
    color: purple



aux_links:
  OpenDSU on GitHub: https://github.com/opendsu/
