title: OpenDSU RFC Documentation
description: OpenDSU RFC Documentation
theme: just-the-docs

#logo: "/LOGO/DSU LOGO.png"

favicon_ico: "/LOGO/DSU LOGO.png"

url: https://opendsu.org

repository: https://github.com/OpenDSU/docssite/tree/main # for github-metadata

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

aux_links:
  "OpenDSU on GitHub":
    - "https://github.com/OpenDSU/docssite/tree/main"

    # Makes Aux links open in a new tab. Default is true
aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: OpenDSU on GitHub
    url: https://github.com/OpenDSU/docssite/tree/main

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
